import type { Metadata } from 'next'
import './globals.css'
import { Nunito } from 'next/font/google'
import { Ubuntu } from 'next/font/google'
import { Comfortaa } from 'next/font/google'
import Navbar from './components/navbar/Navbar'
import ClientOnly from './components/ClientOnly'

import RegisterModal from './components/modals/RegisterModal'
import LoginModal from './components/modals/LoginModal'
import RentModal from './components/modals/RentModal'
import SearchModal from './components/modals/SearchModal'

import ToasterProvider from './providers/ToasterProvider'
import getCurrentUser from './actions/getCurrentUser';


export const metadata: Metadata = {
  title: 'Airbnb NextJS',
  description: 'Generated by create next app',
}

const nunito = Nunito({
  subsets: ['latin']
})

const ubuntu = Ubuntu({
  subsets: ['latin',],
  weight: ["400"],
})

const confotaa = Comfortaa({
  subsets: ['latin',],
  weight: ["400"],
})

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currentUser = await getCurrentUser();


  return (
    <html lang="en">
      <body className={confotaa.className}>
        <ClientOnly>

          <ToasterProvider />
          <SearchModal />
          <LoginModal />
          <RegisterModal />
          <RentModal />

          <Navbar currentUser={currentUser} />
        </ClientOnly>
        <div className="pb-20 pt-28">
          {children}
        </div>
      </body>
    </html>
  )
}
